# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jxrfDTFi2b8EkuQsLddz9Crfi9qaJdBy

Create a text file named "original_data.txt" with the following content:

Name: Preeti Rana
Account Number: 1234567890

Use the following code to replace and restore data in the text file:

Pdf file can be converted to text file or vice versa..And took some data as mentioned
"""

import random

# Read data from the file
with open("original_data.txt", "r") as file:
    original_data = file.read()

# Define a dictionary of replacement values
replacement_dict = {
    "Name:": ["Preeti", "Neha", "Priya"],
    "Account Number:": ["9876543210", "5555555555", "1111111111"]
}

# Function to replace information with synthetic data
def replace_with_synthetic(data, replacement_dict):
    for key, values in replacement_dict.items():
        replacement = random.choice(values)
        data = data.replace(key, replacement, 1)  # Replace only the first occurrence
    return data

# Replace confidential information with synthetic data
synthetic_data = replace_with_synthetic(original_data, replacement_dict)

# Write the synthetic data to a new file
with open("synthetic_data.txt", "w") as file:
    file.write(synthetic_data)

# Function to restore synthetic data back to original data
def restore_to_original(synthetic_data, replacement_dict):
    original_data = synthetic_data
    for key, values in replacement_dict.items():
        for value in values:
            original_data = original_data.replace(value, key, 1)  # Replace only the first occurrence
    return original_data

# Restore synthetic data back to original data
restored_data = restore_to_original(synthetic_data, replacement_dict)

# Print the restored data
print("Restored Data:")
print(restored_data)

"""Please replace "original_data.txt" with your actual file path and customize the replacement_dict with appropriate values."""